#!/bin/bash
# Complete Touchscreen Setup Script for Pi 5
# Waveshare 7.9" HDMI LCD with USB Touchscreen

set -e  # Exit on error

echo "=========================================="
echo "Touchscreen Setup Script"
echo "Waveshare 7.9\" HDMI LCD - Pi 5"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DISPLAY_RESOLUTION_X=1280
DISPLAY_RESOLUTION_Y=400
TOUCHSCREEN_VENDOR_ID="0712"
TOUCHSCREEN_PRODUCT_ID="000a"
TOUCHSCREEN_NAME="WaveShare"

# Step 1: Check if touchscreen is connected
echo "Step 1: Checking for touchscreen..."
USB_DEVICE=$(lsusb | grep -i "$TOUCHSCREEN_VENDOR_ID:$TOUCHSCREEN_PRODUCT_ID" || true)

if [ -z "$USB_DEVICE" ]; then
    echo -e "${RED}ERROR: Touchscreen not found!${NC}"
    echo "Looking for USB device: $TOUCHSCREEN_VENDOR_ID:$TOUCHSCREEN_PRODUCT_ID"
    echo ""
    echo "Available USB devices:"
    lsusb
    echo ""
    echo "Please check:"
    echo "1. Is the USB cable connected?"
    echo "2. Is the touchscreen powered?"
    echo "3. Try unplugging and replugging the USB cable"
    exit 1
fi

echo -e "${GREEN}✓ Touchscreen found:${NC} $USB_DEVICE"
echo ""

# Step 2: Check if input device exists
echo "Step 2: Checking input devices..."
INPUT_DEVICE=$(ls -la /dev/input/ | grep -i event | grep -v "event0" | head -1 | awk '{print $NF}' || true)

if [ -z "$INPUT_DEVICE" ]; then
    echo -e "${RED}ERROR: No input devices found!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Input devices found${NC}"
echo ""

# Step 3: Check if X11 is running
echo "Step 3: Checking X11..."
if [ -z "$DISPLAY" ]; then
    export DISPLAY=:0
fi

if ! xset q &>/dev/null; then
    echo -e "${YELLOW}WARNING: X11 not running. Will configure for when X11 starts.${NC}"
    X11_RUNNING=false
else
    echo -e "${GREEN}✓ X11 is running${NC}"
    X11_RUNNING=true
fi
echo ""

# Step 4: Find touchscreen device in xinput
if [ "$X11_RUNNING" = true ]; then
    echo "Step 4: Finding touchscreen in xinput..."
    TOUCH_DEVICE=$(xinput list | grep -i "$TOUCHSCREEN_NAME" | head -1 || true)
    
    if [ -z "$TOUCH_DEVICE" ]; then
        echo -e "${YELLOW}WARNING: Touchscreen not found in xinput list${NC}"
        echo "Available devices:"
        xinput list
        echo ""
        echo "This might be normal if X11 just started. Will configure anyway."
        TOUCH_DEVICE_ID=""
    else
        TOUCH_DEVICE_ID=$(echo "$TOUCH_DEVICE" | grep -oP 'id=\K[0-9]+')
        echo -e "${GREEN}✓ Touchscreen found in xinput: ID $TOUCH_DEVICE_ID${NC}"
        echo "Device: $TOUCH_DEVICE"
    fi
    echo ""
fi

# Step 5: Get current transformation matrix
if [ "$X11_RUNNING" = true ] && [ ! -z "$TOUCH_DEVICE_ID" ]; then
    echo "Step 5: Checking current transformation matrix..."
    CURRENT_MATRIX=$(xinput list-props "$TOUCH_DEVICE_ID" 2>/dev/null | grep "Coordinate Transformation Matrix" | awk '{print $5, $6, $7, $8, $9, $10, $11, $12, $13}' || echo "")
    
    if [ ! -z "$CURRENT_MATRIX" ]; then
        echo "Current matrix: $CURRENT_MATRIX"
    else
        echo "No transformation matrix found (using default)"
    fi
    echo ""
fi

# Step 6: Calculate correct transformation matrix
echo "Step 6: Calculating transformation matrix..."
echo "Display resolution: ${DISPLAY_RESOLUTION_X}x${DISPLAY_RESOLUTION_Y} (Landscape)"
echo ""

# For Landscape mode (1280x400), no rotation needed
# Matrix: [1 0 0; 0 1 0; 0 0 1]
TRANSFORM_MATRIX="1 0 0 0 1 0 0 0 1"

echo "Transformation matrix: $TRANSFORM_MATRIX"
echo ""

# Step 7: Apply transformation (if X11 running)
if [ "$X11_RUNNING" = true ] && [ ! -z "$TOUCH_DEVICE_ID" ]; then
    echo "Step 7: Applying transformation matrix..."
    xinput set-prop "$TOUCH_DEVICE_ID" "Coordinate Transformation Matrix" $TRANSFORM_MATRIX
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Transformation matrix applied${NC}"
        
        # Verify
        VERIFIED_MATRIX=$(xinput list-props "$TOUCH_DEVICE_ID" 2>/dev/null | grep "Coordinate Transformation Matrix" | awk '{print $5, $6, $7, $8, $9, $10, $11, $12, $13}')
        echo "Verified matrix: $VERIFIED_MATRIX"
    else
        echo -e "${RED}ERROR: Failed to apply transformation matrix${NC}"
        exit 1
    fi
    echo ""
fi

# Step 8: Create permanent configuration
echo "Step 8: Creating permanent configuration..."

# Create xorg.conf.d directory if it doesn't exist
XORG_CONF_DIR="/etc/X11/xorg.conf.d"
if [ ! -d "$XORG_CONF_DIR" ]; then
    echo "Creating $XORG_CONF_DIR..."
    sudo mkdir -p "$XORG_CONF_DIR"
fi

# Create touchscreen configuration
XORG_CONF_FILE="$XORG_CONF_DIR/99-touchscreen.conf"
echo "Creating $XORG_CONF_FILE..."

sudo tee "$XORG_CONF_FILE" > /dev/null << EOF
# Touchscreen Configuration for Waveshare 7.9" HDMI LCD
# Generated by setup_touchscreen.sh

Section "InputClass"
    Identifier "WaveShare Touchscreen"
    MatchUSBID "0712:000a"
    MatchIsTouchscreen "on"
    Driver "libinput"
    Option "TransformationMatrix" "$TRANSFORM_MATRIX"
    Option "CalibrationMatrix" "$TRANSFORM_MATRIX"
EndSection
EOF

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ X11 configuration created${NC}"
else
    echo -e "${RED}ERROR: Failed to create X11 configuration${NC}"
    exit 1
fi
echo ""

# Step 9: Create xinitrc script
echo "Step 9: Creating xinitrc touchscreen configuration..."

XINITRC_TOUCH_SCRIPT="$HOME/.xinitrc_touchscreen"
cat > "$XINITRC_TOUCH_SCRIPT" << 'XINITRC_EOF'
#!/bin/bash
# Touchscreen configuration for xinitrc
# This will be sourced by xinitrc

# Wait for X11 to be ready
sleep 2

# Find touchscreen device
TOUCH_DEVICE=$(xinput list | grep -i "WaveShare" | head -1 | grep -oP 'id=\K[0-9]+')

if [ ! -z "$TOUCH_DEVICE" ]; then
    # Apply transformation matrix for Landscape (1280x400)
    xinput set-prop "$TOUCH_DEVICE" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    echo "Touchscreen configured: Device ID $TOUCH_DEVICE"
else
    echo "Touchscreen not found in xinput"
fi
XINITRC_EOF

chmod +x "$XINITRC_TOUCH_SCRIPT"
echo -e "${GREEN}✓ xinitrc script created${NC}"
echo ""

# Step 10: Instructions for xinitrc integration
echo "Step 10: xinitrc integration instructions..."
echo ""
echo "Add this to your ~/.xinitrc (before Chromium starts):"
echo "----------------------------------------"
echo "source ~/.xinitrc_touchscreen"
echo "----------------------------------------"
echo ""

# Step 11: Test touchscreen (if X11 running)
if [ "$X11_RUNNING" = true ] && [ ! -z "$TOUCH_DEVICE_ID" ]; then
    echo "Step 11: Testing touchscreen..."
    echo ""
    echo "Touch the screen now. You should see coordinates below:"
    echo "Press Ctrl+C to stop testing"
    echo ""
    
    timeout 10 xinput test "$TOUCH_DEVICE_ID" 2>/dev/null || echo "Test completed or device not responding"
    echo ""
fi

# Step 12: Summary
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo -e "${GREEN}Configuration created:${NC}"
echo "  - X11 config: $XORG_CONF_FILE"
echo "  - xinitrc script: $XINITRC_TOUCH_SCRIPT"
echo ""
echo "Next steps:"
echo "1. Add 'source ~/.xinitrc_touchscreen' to your ~/.xinitrc"
echo "2. Reboot or restart X11"
echo "3. Test touchscreen coordinates"
echo ""
echo "To test touchscreen:"
echo "  xinput test <device_id>"
echo ""
echo "To verify matrix:"
echo "  xinput list-props <device_id> | grep Transformation"
echo ""

